spring.application.name=aulahoje

# Configuração do Banco de dados -> Conexão
spring.datasource.url=jdbc:h2:file:./data/auladb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Configura o Hibernate para criar as requisições SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Atualiza o banco de dados (automaticamente)
spring.jpa.hibernate.ddl-auto=update

# Configurar para mostrar as requisições SQL no console
spring.jpa.show=true

# Formatar as requisições SQL
spring.jpa.properties.hibernate.format_sql=true
